#!/usr/bin/env python3
"""Generate the built-in conveyor, table, and reusable workpiece accessory packages."""

from __future__ import annotations

import json
import math
from pathlib import Path

from pkglib import LIBRARY_PACKAGES, LIBRARY_SOURCES
from pkglib.archive import write_zip
from pkglib.geom import append_box, append_perforated_cell, append_z_cylinder
from pkglib.meshbin import write_meshbin
from pkglib.nodes import mesh_node, root_node, transform_node


def write_package(package_dir: Path, archive_path: Path, manifest: dict,
                  meshes: dict[str, tuple[list[float], list[int]]]) -> None:
    package_dir.mkdir(parents=True, exist_ok=True)
    for relative_path, (vertices, indices) in meshes.items():
        write_meshbin(package_dir / relative_path, vertices, indices)
    (package_dir / "accessory.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                                encoding="utf-8")
    # Zip only the named members: several packages share one mesh dict, and a stale file in the
    # package directory must not ride along.
    write_zip(package_dir, archive_path, members=["accessory.json", *sorted(meshes)])


def generate_roller_conveyor() -> None:
    default_roller_pitch_mm = 100.0
    default_roller_radius_mm = max(4.0, min(32.0, default_roller_pitch_mm * 0.45))
    steel_vertices: list[float] = []
    steel_indices: list[int] = []
    dark_vertices: list[float] = []
    dark_indices: list[int] = []
    roller_vertices: list[float] = []
    roller_indices: list[int] = []
    cover_vertices: list[float] = []
    cover_indices: list[int] = []

    # Two side rails, end ties and lower bracing.
    for z in (-330.0, 330.0):
        append_box(steel_vertices, steel_indices, (0.0, 820.0, z), (1800.0, 140.0, 40.0))
        append_box(steel_vertices, steel_indices, (0.0, 360.0, z), (1500.0, 45.0, 45.0))
    for x in (-880.0, 880.0):
        append_box(steel_vertices, steel_indices, (x, 820.0, 0.0), (40.0, 140.0, 620.0))
    for x in (-700.0, 700.0):
        for z in (-280.0, 280.0):
            append_box(steel_vertices, steel_indices, (x, 390.0, z), (60.0, 760.0, 60.0))
            append_box(dark_vertices, dark_indices, (x, 5.0, z), (130.0, 10.0, 130.0))
    roller_inset = default_roller_radius_mm
    roller_run = 1800.0 - roller_inset * 2.0
    roller_count = max(2, math.floor(roller_run / default_roller_pitch_mm) + 1)
    for index in range(roller_count):
        x = -900.0 + roller_inset + roller_run * index / (roller_count - 1)
        # Keep every roller crown on the 890 mm deck plane as fine pitches reduce diameter.
        append_z_cylinder(roller_vertices, roller_indices, x,
                          890.0 - default_roller_radius_mm,
                          -305.0, 305.0, default_roller_radius_mm)
    # Static package preview; the runtime generator replaces this with path-following belt patches
    # when rollerCoverEnabled is selected.
    append_box(cover_vertices, cover_indices, (0.0, 895.0, 0.0),
               (1800.0, 6.0, 626.0))

    source_holes = {
        "comment": ("Four virtual floor mounting centers at the roller conveyor foot-plate "
                    "centers. Generated by scripts/generate_accessory_packages.py."),
        "placementSource": True,
        "grids": [{
            "originMm": [-700.0, 0.0, -280.0],
            "uStepMm": [1400.0, 0.0, 0.0],
            "vStepMm": [0.0, 0.0, 560.0],
            "uCount": 2,
            "vCount": 2,
        }],
    }
    def end_connection_holes(end_name: str, interface_id: str,
                             height_parameter: str) -> dict:
        return {
            "comment": (f"Four virtual {end_name} conveyor connection centers over the "
                        "upper/lower rail corners. This is an oriented placement-source and snap "
                        "target interface. Generated by scripts/generate_accessory_packages.py."),
            "placementSource": True,
            "mateOpposite": True,
            "interfaceId": interface_id,
            "parameterBindings": {"deckHeight": height_parameter},
            "grids": [{
                "originMm": [0.0, 0.0, -330.0],
                "uStepMm": [140.0, 0.0, 0.0],
                "vStepMm": [0.0, 0.0, 660.0],
                "uCount": 2,
                "vCount": 2,
            }],
        }

    manifest = root_node("Roller Conveyor", [
        mesh_node("Powder-coated frame", "meshes/frame.meshbin",
                  [0.16, 0.19, 0.22, 1.0]),
        mesh_node("Adjustable feet", "meshes/feet.meshbin", [0.08, 0.09, 0.10, 1.0]),
        mesh_node("Steel rollers", "meshes/rollers.meshbin", [0.68, 0.71, 0.73, 1.0]),
        # Local Y is the interface normal. These rotations make it point out of each end while
        # local X spans the lower/upper pair, allowing the snap solver to mate end planes.
        transform_node("Left end connection",
                       [0.0, -1.0, 0.0, -900.0,
                        1.0,  0.0, 0.0,  750.0,
                        0.0,  0.0, 1.0,    0.0],
                       end_connection_holes("left-end", "start", "startHeightMm")),
        transform_node("Right end connection",
                       [0.0,  1.0, 0.0, 900.0,
                        1.0,  0.0, 0.0, 750.0,
                        0.0,  0.0, -1.0,  0.0],
                       end_connection_holes("right-end", "end", "endHeightMm")),
        mesh_node("Black roller cover", "meshes/cover.meshbin", [0.03, 0.035, 0.04, 1.0]),
    ], source_holes, {
        "generator": "roller_conveyor",
        "widthMm": 700.0,
        "lengthMm": 1800.0,
        "heightMm": 890.0,
        "rollerPitchMm": default_roller_pitch_mm,
        "startHeightMm": 890.0,
        "endHeightMm": 890.0,
        "startLeftHeightMm": 890.0,
        "startRightHeightMm": 890.0,
        "endLeftHeightMm": 890.0,
        "endRightHeightMm": 890.0,
        "turnAngleDeg": 0.0,
        "curveRadiusMm": 900.0,
        "supportBracesEnabled": True,
        "rollerCoverEnabled": False,
        "endStopEnabled": False,
        "simulationMode": "global",
        "role": "normal",
        "speedMmS": 250.0,
        "spawnIntervalSeconds": 1.0,
        "maxActiveSpawns": 0,
    })
    common = {
        "generator": "roller_conveyor",
        "widthMm": 700.0,
        "lengthMm": 1800.0,
        "rollerPitchMm": default_roller_pitch_mm,
        "curveRadiusMm": 900.0,
        "supportBracesEnabled": True,
        "rollerCoverEnabled": False,
        "endStopEnabled": False,
        "simulationMode": "global",
        "role": "normal",
        "speedMmS": 250.0,
        "spawnIntervalSeconds": 1.0,
        "maxActiveSpawns": 0,
    }
    manifest["libraryVariants"] = [
        {
            "id": "straight-890",
            "name": "Straight Conveyor — 1.8 m",
            "parameters": {**common, "heightMm": 890.0, "startHeightMm": 890.0,
                           "endHeightMm": 890.0, "startLeftHeightMm": 890.0,
                           "startRightHeightMm": 890.0, "endLeftHeightMm": 890.0,
                           "endRightHeightMm": 890.0, "turnAngleDeg": 0.0},
        },
        {
            "id": "corner-left-90",
            "name": "Left 90 deg Conveyor — R0.9 m",
            "parameters": {**common, "heightMm": 890.0, "startHeightMm": 890.0,
                           "endHeightMm": 890.0, "startLeftHeightMm": 890.0,
                           "startRightHeightMm": 890.0, "endLeftHeightMm": 890.0,
                           "endRightHeightMm": 890.0, "turnAngleDeg": 90.0},
        },
        {
            "id": "corner-right-90",
            "name": "Right 90 deg Conveyor — R0.9 m",
            "parameters": {**common, "heightMm": 890.0, "startHeightMm": 890.0,
                           "endHeightMm": 890.0, "startLeftHeightMm": 890.0,
                           "startRightHeightMm": 890.0, "endLeftHeightMm": 890.0,
                           "endRightHeightMm": 890.0, "turnAngleDeg": -90.0},
        },
        {
            "id": "spiral-ascending-720",
            "name": "2-Turn Spiral Conveyor — +1.8 m",
            "parameters": {**common, "heightMm": 1790.0, "startHeightMm": 890.0,
                           "endHeightMm": 2690.0, "startLeftHeightMm": 890.0,
                           "startRightHeightMm": 890.0, "endLeftHeightMm": 2690.0,
                           "endRightHeightMm": 2690.0, "turnAngleDeg": 720.0,
                           "supportBracesEnabled": False},
        },
        {
            "id": "object-spawner",
            "name": "Object Spawner Conveyor",
            "parameters": {**common, "heightMm": 890.0, "startHeightMm": 890.0,
                           "endHeightMm": 890.0, "startLeftHeightMm": 890.0,
                           "startRightHeightMm": 890.0, "endLeftHeightMm": 890.0,
                           "endRightHeightMm": 890.0, "turnAngleDeg": 0.0,
                           "rollerCoverEnabled": True, "simulationMode": "physx",
                           "role": "spawner"},
        },
        {
            "id": "pick-accumulator-right-bank",
            "name": "Pick Accumulator - Right Bank",
            "parameters": {**common, "heightMm": 865.0, "startHeightMm": 890.0,
                           "endHeightMm": 840.0, "startLeftHeightMm": 890.0,
                           "startRightHeightMm": 890.0, "endLeftHeightMm": 890.0,
                           "endRightHeightMm": 790.0, "turnAngleDeg": 0.0,
                           "rollerCoverEnabled": True, "endStopEnabled": True,
                           "simulationMode": "physx", "speedMmS": 180.0},
        },
        {
            "id": "deleter",
            "name": "Deleter Conveyor",
            "parameters": {**common, "heightMm": 890.0, "startHeightMm": 890.0,
                           "endHeightMm": 890.0, "startLeftHeightMm": 890.0,
                           "startRightHeightMm": 890.0, "endLeftHeightMm": 890.0,
                           "endRightHeightMm": 890.0, "turnAngleDeg": 0.0,
                           "role": "deleter"},
        },
    ]
    conveyor_meshes = {
        "meshes/frame.meshbin": (steel_vertices, steel_indices),
        "meshes/feet.meshbin": (dark_vertices, dark_indices),
        "meshes/rollers.meshbin": (roller_vertices, roller_indices),
        "meshes/cover.meshbin": (cover_vertices, cover_indices),
    }
    write_package(LIBRARY_SOURCES / "roller_conveyor", LIBRARY_PACKAGES / "roller_conveyor.zip",
                  manifest, conveyor_meshes)

    # A separate catalogue item backed by the shared conveyor runtime. role=pick_feeder selects a
    # dedicated, monotonic single-file funnel profile and a short top-access pickup pocket. The
    # compact centre platform supports the workpiece, the walls follow the visible deck profile,
    # and a full-height terminal wall locates the workpiece. Rendering and native PhysX boxes
    # derive from those shared profiles at runtime.
    feeder_parameters = {
        **common,
        "widthMm": 300.0,
        "lengthMm": 700.0,
        "heightMm": 775.0,
        "startHeightMm": 800.0,
        "endHeightMm": 750.0,
        "startLeftHeightMm": 800.0,
        "startRightHeightMm": 800.0,
        "endLeftHeightMm": 750.0,
        "endRightHeightMm": 750.0,
        "turnAngleDeg": 0.0,
        "supportBracesEnabled": True,
        "rollerCoverEnabled": True,
        "endStopEnabled": True,
        "simulationMode": "physx",
        "role": "pick_feeder",
        "speedMmS": 120.0,
    }
    feeder_manifest = root_node("Robot Pick Feeder", [
        mesh_node("Powder-coated frame", "meshes/frame.meshbin",
                  [0.16, 0.19, 0.22, 1.0]),
        mesh_node("Adjustable feet", "meshes/feet.meshbin", [0.08, 0.09, 0.10, 1.0]),
        mesh_node("Steel rollers", "meshes/rollers.meshbin", [0.68, 0.71, 0.73, 1.0]),
        transform_node("Left end connection",
                       [0.0, -1.0, 0.0, -350.0,
                        1.0,  0.0, 0.0,  660.0,
                        0.0,  0.0, 1.0,    0.0],
                       end_connection_holes("left-end", "start", "startHeightMm")),
        transform_node("Right end connection",
                       [0.0,  1.0, 0.0, 350.0,
                        1.0,  0.0, 0.0, 610.0,
                        0.0,  0.0, -1.0, 0.0],
                       {
                           "comment": ("Robot pick pocket: deliberately not a conveyor snap "
                                       "interface. Generated by "
                                       "scripts/generate_accessory_packages.py."),
                           "placementSource": False,
                       }),
        mesh_node("Black roller cover", "meshes/cover.meshbin", [0.03, 0.035, 0.04, 1.0]),
    ], {
        "comment": ("Four virtual floor mounting centers generated from the feeder support "
                    "feet by scripts/generate_accessory_packages.py."),
        "placementSource": True,
        "grids": [{
            "originMm": [-260.0, 0.0, -80.0],
            "uStepMm": [390.0, 0.0, 0.0],
            "vStepMm": [0.0, 0.0, 160.0],
            "uCount": 2,
            "vCount": 2,
        }],
    }, feeder_parameters)
    write_package(LIBRARY_SOURCES / "robot_pick_feeder",
                  LIBRARY_PACKAGES / "robot_pick_feeder.zip",
                  feeder_manifest, conveyor_meshes)


def generate_ar4_table() -> None:
    frame_vertices: list[float] = []
    frame_indices: list[int] = []
    top_vertices: list[float] = []
    top_indices: list[int] = []
    foot_vertices: list[float] = []
    foot_indices: list[int] = []

    for x in (-330.0, 330.0):
        for z in (-330.0, 330.0):
            append_box(frame_vertices, frame_indices, (x, 390.0, z), (60.0, 760.0, 60.0))
            append_box(foot_vertices, foot_indices, (x, 5.0, z), (120.0, 10.0, 120.0))
    for y in (120.0, 690.0):
        for z in (-330.0, 330.0):
            append_box(frame_vertices, frame_indices, (0.0, y, z), (720.0, 45.0, 45.0))
        for x in (-330.0, 330.0):
            append_box(frame_vertices, frame_indices, (x, y, 0.0), (45.0, 45.0, 720.0))

    # Forty-nine true through holes in a 7x7, 100 mm-pitch steel plate.
    for x in range(-300, 301, 100):
        for z in range(-300, 301, 100):
            append_perforated_cell(top_vertices, top_indices, float(x), float(z),
                                   800.0, 820.0, 100.0, 7.0)
    append_box(top_vertices, top_indices, (-375.0, 810.0, 0.0), (50.0, 20.0, 800.0))
    append_box(top_vertices, top_indices, (375.0, 810.0, 0.0), (50.0, 20.0, 800.0))
    append_box(top_vertices, top_indices, (0.0, 810.0, -375.0), (700.0, 20.0, 50.0))
    append_box(top_vertices, top_indices, (0.0, 810.0, 375.0), (700.0, 20.0, 50.0))

    source_holes = {
        "comment": ("Four virtual floor mounting centers at the AR4 table foot-plate centers. "
                    "Generated by scripts/generate_accessory_packages.py."),
        "placementSource": True,
        "grids": [{
            "originMm": [-330.0, 0.0, -330.0],
            "uStepMm": [660.0, 0.0, 0.0],
            "vStepMm": [0.0, 0.0, 660.0],
            "uCount": 2,
            "vCount": 2,
        }],
    }
    top_holes = {
        "comment": ("Seven by seven M8-clearance through-hole pattern on 100 mm pitch. The pitch "
                    "matches the AR4 external 100 by 100 mm base mounting pattern. Generated by "
                    "scripts/generate_accessory_packages.py."),
        "grids": [{
            "originMm": [-300.0, 820.0, -300.0],
            "uStepMm": [100.0, 0.0, 0.0],
            "vStepMm": [0.0, 0.0, 100.0],
            "uCount": 7,
            "vCount": 7,
        }],
    }
    manifest = root_node("AR4 Table — 100 mm pitch", [
        mesh_node("Welded frame", "meshes/frame.meshbin", [0.25, 0.28, 0.31, 1.0]),
        mesh_node("Floor plates", "meshes/feet.meshbin", [0.10, 0.11, 0.12, 1.0]),
        mesh_node("100 mm pitch perforated steel top", "meshes/top.meshbin",
                  [0.70, 0.73, 0.75, 1.0], top_holes),
    ], source_holes, {
        "generator": "ar4_table",
        "widthMm": 800.0,
        "lengthMm": 800.0,
        "heightMm": 820.0,
        "holePitchMm": 100.0,
    })
    write_package(LIBRARY_SOURCES / "ar4_table_100mm_pitch",
                  LIBRARY_PACKAGES / "ar4_table_100mm_pitch.zip", manifest, {
                      "meshes/frame.meshbin": (frame_vertices, frame_indices),
                      "meshes/feet.meshbin": (foot_vertices, foot_indices),
                      "meshes/top.meshbin": (top_vertices, top_indices),
                  })


def generate_box_workpiece() -> None:
    """A station-owned prototype that spawners clone; centered for visual/physics agreement."""
    vertices: list[float] = []
    indices: list[int] = []
    append_box(vertices, indices, (0.0, 0.0, 0.0), (120.0, 100.0, 120.0))
    placement_holes = {
        "comment": "Four virtual bottom-corner placement centers for the reusable box workpiece.",
        "placementSource": True,
        "grids": [{
            "originMm": [-50.0, -50.0, -50.0],
            "uStepMm": [100.0, 0.0, 0.0],
            "vStepMm": [0.0, 0.0, 100.0],
            "uCount": 2,
            "vCount": 2,
        }],
    }
    manifest = root_node("Box workpiece", [
        mesh_node("Box model", "meshes/box.meshbin", [0.925, 0.541, 0.165, 1.0]),
    ], placement_holes)
    write_package(LIBRARY_SOURCES / "box_workpiece",
                  LIBRARY_PACKAGES / "box_workpiece.zip", manifest, {
                      "meshes/box.meshbin": (vertices, indices),
                  })


def generate_hand_e_box_workpiece() -> None:
    """A compact payload whose 30 mm grip width fits the Hand-E's physical finger stroke."""
    vertices: list[float] = []
    indices: list[int] = []
    append_box(vertices, indices, (0.0, 0.0, 0.0), (30.0, 30.0, 30.0))
    placement_holes = {
        "comment": "Four virtual bottom-corner placement centers for the 30 mm Hand-E workpiece.",
        "placementSource": True,
        "grids": [{
            "originMm": [-10.0, -15.0, -10.0],
            "uStepMm": [20.0, 0.0, 0.0],
            "vStepMm": [0.0, 0.0, 20.0],
            "uCount": 2,
            "vCount": 2,
        }],
    }
    manifest = root_node("Hand-E box 30 mm", [
        mesh_node("Box model", "meshes/box.meshbin", [0.925, 0.541, 0.165, 1.0]),
    ], placement_holes)
    manifest["libraryCategory"] = "model"
    write_package(LIBRARY_SOURCES / "hand_e_box_workpiece",
                  LIBRARY_PACKAGES / "hand_e_box_workpiece.zip", manifest, {
                      "meshes/box.meshbin": (vertices, indices),
                  })


def main() -> None:
    generate_roller_conveyor()
    generate_ar4_table()
    generate_box_workpiece()
    generate_hand_e_box_workpiece()
    print("wrote conveyor, table, and workpiece packages")


if __name__ == "__main__":
    main()
